# Generated by Django 5.0.7 on 2025-04-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
